export const dndTypes = {
  ADD_TEXT: "ADD_TEXT",
  ADD_IMAGE: "ADD_IMAGE",
  ADD_RECTANGLE: "ADD_RECTANGLE",
  EDITING_TEXT: "EDITING_TEXT",
  EDITING_IMAGE: "EDITING_IMAGE",
  EDITING_RECTANGLE: "EDITING_RECTANGLE",
};
